# Generated by Django 2.2.10 on 2021-03-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeproduct_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproduct',
            old_name='profile_pic',
            new_name='productPic',
        ),
    ]
