# Generated by Django 2.2.10 on 2021-03-27 01:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_storeproduct_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[640, 360], upload_to='whatever'),
        ),
    ]
