# Generated by Django 2.2.10 on 2021-03-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210327_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='image1',
        ),
    ]
