# Generated by Django 4.2.11 on 2024-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_auto_20210403_0625"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Pending"),
                    ("1", "Out for delivery"),
                    ("2", "Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
