# Generated by Django 4.2.11 on 2024-12-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_storeorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Pending"),
                    ("1", "Out for delivery"),
                    ("2", "Delivered"),
                ],
                default=0,
                max_length=200,
                null=True,
            ),
        ),
    ]
