# Generated by Django 4.2.11 on 2025-01-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_wishlistitem_delete_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="refund_requested",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
