# Generated by Django 4.2.11 on 2025-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_storeorder_refund_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeorder",
            name="refund_status",
            field=models.CharField(
                blank=True,
                choices=[("0", "Pending"), ("1", "Approved"), ("2", "Declined")],
                default=0,
                max_length=200,
                null=True,
            ),
        ),
    ]
