# Generated by Django 4.2.11 on 2025-01-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_productreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, help_text="Discount percentage", max_digits=5
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="storeorder",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.promocode",
            ),
        ),
    ]
