# Generated by Django 4.2.11 on 2025-01-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_productcomparison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
