# Generated by Django 2.1 on 2021-02-11 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210212_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Tag',
            new_name='tags',
        ),
    ]
